AWSTemplateFormatVersion: "2010-09-09"
Description: >
  This template creates an Aurora RDS Serverless v2 PostgreSQL instance with minimal resource allocation.
  The instance is placed in the specified VPC and private subnets, and it uses a secret in AWS Secrets Manager for database credentials.

Parameters:
  DBUsername:
    Description: The database master user name.
    Type: String
    Default: prodadmin
  
  DBName:
    Description: The name of the initial database.
    Type: String
    Default: prodec2instancedata

  RDSClusterName:
    Description: The name of the RDS cluster.
    Type: String
    Default: prod-infra-data

  VPCId:
    Description: The ID of the VPC where the RDS cluster will be deployed.
    Type: AWS::EC2::VPC::Id

  SubnetId1:
    Description: The ID of the first private subnet.
    Type: AWS::EC2::Subnet::Id

  SubnetId2:
    Description: The ID of the second private subnet.
    Type: AWS::EC2::Subnet::Id

  SecurityGroupId:
    Description: The ID of the security group to associate with the RDS cluster.
    Type: AWS::EC2::SecurityGroup::Id

  SecretName:
    Description: The name of the Secrets Manager secret for the RDS credentials.
    Type: String
    Default: prod-infra-data-db-secret

Resources:
  # Secret in Secrets Manager for storing DB credentials
  RDSSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Ref SecretName
      Description: RDS credentials for Aurora Serverless v2
      GenerateSecretString:
        SecretStringTemplate: !Sub '{"username": "${DBUsername}"}'
        GenerateStringKey: "password"
        PasswordLength: 16
        ExcludeCharacters: '"@/\\'
      Tags:
        - Key: Name
          Value: RDSSecret

  # Aurora DB Cluster for Serverless v2 with minimal resources
  AuroraDBCluster:
    Type: AWS::RDS::DBCluster
    Properties: 
      Engine: aurora-postgresql
      EngineVersion: "15.4"
      DBClusterIdentifier: !Ref RDSClusterName
      DatabaseName: !Ref DBName
      MasterUsername: !Sub "{{resolve:secretsmanager:${SecretName}:SecretString:username}}"
      MasterUserPassword: !Sub "{{resolve:secretsmanager:${SecretName}:SecretString:password}}"
      DBClusterParameterGroupName: default.aurora-postgresql15
      EnableHttpEndpoint: true  # Enables the Data API
      ServerlessV2ScalingConfiguration:
        MinCapacity: 0.5  # Very minimal resources
        MaxCapacity: 1    # Minimal resources for cost-efficiency
      StorageEncrypted: true
      DeletionProtection: false
      VpcSecurityGroupIds:
        - !Ref SecurityGroupId
      DBSubnetGroupName: !Ref DBSubnetGroup
      EnableIAMDatabaseAuthentication: true  # Enable IAM Authentication
      BackupRetentionPeriod: 1  # Minimal backup period to reduce costs
      Tags:
        - Key: Name
          Value: !Ref RDSClusterName

  # DB Subnet Group for RDS, using the two private subnets
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties: 
      DBSubnetGroupDescription: Subnet group for RDS Serverless v2
      SubnetIds: 
        - !Ref SubnetId1
        - !Ref SubnetId2
      Tags:
        - Key: Name
          Value: RDS DB Subnet Group

Outputs:
  RDSClusterEndpoint:
    Description: The endpoint of the Aurora RDS Serverless cluster
    Value: !GetAtt AuroraDBCluster.Endpoint.Address

  SecretArn:
    Description: The ARN of the Secrets Manager secret
    Value: !Ref RDSSecret

